# Generated by Django 4.2.7 on 2024-01-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_category_users_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='ref_vk',
            field=models.URLField(blank=True),
        ),
    ]
